# Generated by Django 3.2.7 on 2021-10-06 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitte', '0002_auto_20211003_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tVote', to='twitte.twitte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uVote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
